server:
  port: 8899
blog:
  homeUrl: http://localhost:8081/#/user
databaseName: vueblog
justauth:
  type:
    github:
      client-id: xxx
      client-security: xxx
      redirect-uri: http://xxx/blog/user/callback/github
mysql:
  dump:
    location: D:/
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://my.service.com:3306/VueBlog?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    host: localhost
logging:
  level:
    xyz.yhhu.blog.mapper: debug
