server:
  port: 8899
#  servlet:
#    context-path: /blog
email:
  adminEmail: 1357958736@qq.com
spring:
  profiles:
    active: prod
  flyway:
    locations: ["classpath:db"]
    baseline-on-migrate: true
    placeholder-prefix: ${} # 占位符去掉，数据库数据存在冲突
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
  mail:
    default-encoding: utf-8
    host: smtp.qq.com
    password: xxx
    properties:
      mail:
        display:
          sendmail: 来自yhhu_blog的信息
          sendname: Tiger
        smtp:
          auth: true
          connectiontimeout: 5000
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
          timeout: 10000
          writetimeout: 10000
    username: xxx@qq.com
  mvc:
    static-path-pattern: /**
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: xyz.yhhu.blog.entity
  check-config-location: true
  configuration:
    map-underscore-to-camel-case: true
